# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ORStools/gui/ORStoolsDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ORStoolsDialogBase(object):
    def setupUi(self, ORStoolsDialogBase):
        ORStoolsDialogBase.setObjectName("ORStoolsDialogBase")
        ORStoolsDialogBase.resize(420, 692)
        ORStoolsDialogBase.setSizeGripEnabled(True)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(ORStoolsDialogBase)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.resources_group = QtWidgets.QGroupBox(ORStoolsDialogBase)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resources_group.setFont(font)
        self.resources_group.setAlignment(QtCore.Qt.AlignCenter)
        self.resources_group.setFlat(False)
        self.resources_group.setObjectName("resources_group")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.resources_group)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.resources_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.resources_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.resources_group)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.resources_group)
        self.widget_4 = QtWidgets.QWidget(ORStoolsDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.widget_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.provider_combo = QtWidgets.QComboBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.provider_combo.sizePolicy().hasHeightForWidth())
        self.provider_combo.setSizePolicy(sizePolicy)
        self.provider_combo.setMinimumSize(QtCore.QSize(150, 25))
        self.provider_combo.setObjectName("provider_combo")
        self.horizontalLayout_7.addWidget(self.provider_combo)
        self.provider_refresh = QtWidgets.QPushButton(self.widget_4)
        self.provider_refresh.setText("")
        icon = QtGui.QIcon.fromTheme("reload")
        self.provider_refresh.setIcon(icon)
        self.provider_refresh.setObjectName("provider_refresh")
        self.horizontalLayout_7.addWidget(self.provider_refresh)
        self.provider_config = QtWidgets.QPushButton(self.widget_4)
        self.provider_config.setText("")
        icon = QtGui.QIcon.fromTheme("emblem-system")
        self.provider_config.setIcon(icon)
        self.provider_config.setObjectName("provider_config")
        self.horizontalLayout_7.addWidget(self.provider_config)
        self.quota_text = QtWidgets.QLabel(self.widget_4)
        self.quota_text.setObjectName("quota_text")
        self.horizontalLayout_7.addWidget(self.quota_text)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.tabWidget = QtWidgets.QTabWidget(ORStoolsDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.routing = QtWidgets.QWidget()
        self.routing.setObjectName("routing")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.routing)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.routing_travel_group = QtWidgets.QWidget(self.routing)
        self.routing_travel_group.setObjectName("routing_travel_group")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.routing_travel_group)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.routing_travel_label = QtWidgets.QLabel(self.routing_travel_group)
        self.routing_travel_label.setObjectName("routing_travel_label")
        self.horizontalLayout_2.addWidget(self.routing_travel_label)
        self.routing_travel_combo = QtWidgets.QComboBox(self.routing_travel_group)
        self.routing_travel_combo.setObjectName("routing_travel_combo")
        self.horizontalLayout_2.addWidget(self.routing_travel_combo)
        self.routing_preference_combo = QtWidgets.QComboBox(self.routing_travel_group)
        self.routing_preference_combo.setObjectName("routing_preference_combo")
        self.horizontalLayout_2.addWidget(self.routing_preference_combo)
        self.routing_advanced_button = QtWidgets.QPushButton(self.routing_travel_group)
        self.routing_advanced_button.setObjectName("routing_advanced_button")
        self.horizontalLayout_2.addWidget(self.routing_advanced_button)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout_7.addWidget(self.routing_travel_group)
        self.routing_tab = QtWidgets.QTabWidget(self.routing)
        self.routing_tab.setObjectName("routing_tab")
        self.tab_frompoint = QtWidgets.QWidget()
        self.tab_frompoint.setObjectName("tab_frompoint")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_frompoint)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.routing_frompoint_start_group = QtWidgets.QGroupBox(self.tab_frompoint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_frompoint_start_group.sizePolicy().hasHeightForWidth())
        self.routing_frompoint_start_group.setSizePolicy(sizePolicy)
        self.routing_frompoint_start_group.setObjectName("routing_frompoint_start_group")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.routing_frompoint_start_group)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.routing_frompoint_start_map = QtWidgets.QPushButton(self.routing_frompoint_start_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_frompoint_start_map.sizePolicy().hasHeightForWidth())
        self.routing_frompoint_start_map.setSizePolicy(sizePolicy)
        self.routing_frompoint_start_map.setObjectName("routing_frompoint_start_map")
        self.gridLayout_6.addWidget(self.routing_frompoint_start_map, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.routing_frompoint_start_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.routing_frompoint_start_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 3, 1, 1)
        self.routing_frompoint_start_clear = QtWidgets.QPushButton(self.routing_frompoint_start_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_frompoint_start_clear.sizePolicy().hasHeightForWidth())
        self.routing_frompoint_start_clear.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("process-stop")
        self.routing_frompoint_start_clear.setIcon(icon)
        self.routing_frompoint_start_clear.setObjectName("routing_frompoint_start_clear")
        self.gridLayout_6.addWidget(self.routing_frompoint_start_clear, 1, 0, 1, 1)
        self.routing_frompoint_start_x = QgsFilterLineEdit(self.routing_frompoint_start_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_frompoint_start_x.sizePolicy().hasHeightForWidth())
        self.routing_frompoint_start_x.setSizePolicy(sizePolicy)
        self.routing_frompoint_start_x.setMaximumSize(QtCore.QSize(120, 25))
        self.routing_frompoint_start_x.setProperty("qgisRelation", "")
        self.routing_frompoint_start_x.setObjectName("routing_frompoint_start_x")
        self.gridLayout_6.addWidget(self.routing_frompoint_start_x, 0, 2, 1, 1)
        self.routing_frompoint_start_y = QgsFilterLineEdit(self.routing_frompoint_start_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_frompoint_start_y.sizePolicy().hasHeightForWidth())
        self.routing_frompoint_start_y.setSizePolicy(sizePolicy)
        self.routing_frompoint_start_y.setMaximumSize(QtCore.QSize(120, 25))
        self.routing_frompoint_start_y.setProperty("qgisRelation", "")
        self.routing_frompoint_start_y.setObjectName("routing_frompoint_start_y")
        self.gridLayout_6.addWidget(self.routing_frompoint_start_y, 0, 4, 1, 1)
        self.verticalLayout_6.addWidget(self.routing_frompoint_start_group)
        self.routing_frompoint_end_group = QtWidgets.QGroupBox(self.tab_frompoint)
        self.routing_frompoint_end_group.setObjectName("routing_frompoint_end_group")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.routing_frompoint_end_group)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_10 = QtWidgets.QLabel(self.routing_frompoint_end_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 1, 1, 1)
        self.routing_frompoint_end_map = QtWidgets.QPushButton(self.routing_frompoint_end_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_frompoint_end_map.sizePolicy().hasHeightForWidth())
        self.routing_frompoint_end_map.setSizePolicy(sizePolicy)
        self.routing_frompoint_end_map.setObjectName("routing_frompoint_end_map")
        self.gridLayout_7.addWidget(self.routing_frompoint_end_map, 0, 0, 1, 1)
        self.routing_frompoint_end_clear = QtWidgets.QPushButton(self.routing_frompoint_end_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_frompoint_end_clear.sizePolicy().hasHeightForWidth())
        self.routing_frompoint_end_clear.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("process-stop")
        self.routing_frompoint_end_clear.setIcon(icon)
        self.routing_frompoint_end_clear.setObjectName("routing_frompoint_end_clear")
        self.gridLayout_7.addWidget(self.routing_frompoint_end_clear, 1, 0, 1, 1)
        self.routing_frompoint_end_x = QgsFilterLineEdit(self.routing_frompoint_end_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_frompoint_end_x.sizePolicy().hasHeightForWidth())
        self.routing_frompoint_end_x.setSizePolicy(sizePolicy)
        self.routing_frompoint_end_x.setMaximumSize(QtCore.QSize(120, 25))
        self.routing_frompoint_end_x.setProperty("qgisRelation", "")
        self.routing_frompoint_end_x.setObjectName("routing_frompoint_end_x")
        self.gridLayout_7.addWidget(self.routing_frompoint_end_x, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.routing_frompoint_end_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 0, 3, 1, 1)
        self.routing_frompoint_end_y = QgsFilterLineEdit(self.routing_frompoint_end_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_frompoint_end_y.sizePolicy().hasHeightForWidth())
        self.routing_frompoint_end_y.setSizePolicy(sizePolicy)
        self.routing_frompoint_end_y.setMaximumSize(QtCore.QSize(120, 25))
        self.routing_frompoint_end_y.setProperty("qgisRelation", "")
        self.routing_frompoint_end_y.setObjectName("routing_frompoint_end_y")
        self.gridLayout_7.addWidget(self.routing_frompoint_end_y, 0, 4, 1, 1)
        self.verticalLayout_6.addWidget(self.routing_frompoint_end_group)
        self.routing_tab.addTab(self.tab_frompoint, "")
        self.tab_fromline = QtWidgets.QWidget()
        self.tab_fromline.setObjectName("tab_fromline")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_fromline)
        self.gridLayout.setObjectName("gridLayout")
        self.routing_fromline_map = QtWidgets.QPushButton(self.tab_fromline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_fromline_map.sizePolicy().hasHeightForWidth())
        self.routing_fromline_map.setSizePolicy(sizePolicy)
        self.routing_fromline_map.setObjectName("routing_fromline_map")
        self.gridLayout.addWidget(self.routing_fromline_map, 0, 0, 1, 1)
        self.routing_fromline_remove = QtWidgets.QPushButton(self.tab_fromline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_fromline_remove.sizePolicy().hasHeightForWidth())
        self.routing_fromline_remove.setSizePolicy(sizePolicy)
        self.routing_fromline_remove.setMaximumSize(QtCore.QSize(30, 25))
        self.routing_fromline_remove.setObjectName("routing_fromline_remove")
        self.gridLayout.addWidget(self.routing_fromline_remove, 0, 1, 1, 1)
        self.routing_fromline_list = QtWidgets.QListWidget(self.tab_fromline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_fromline_list.sizePolicy().hasHeightForWidth())
        self.routing_fromline_list.setSizePolicy(sizePolicy)
        self.routing_fromline_list.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.routing_fromline_list.setObjectName("routing_fromline_list")
        self.gridLayout.addWidget(self.routing_fromline_list, 0, 2, 3, 1)
        self.routing_fromline_clear = QtWidgets.QPushButton(self.tab_fromline)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_fromline_clear.sizePolicy().hasHeightForWidth())
        self.routing_fromline_clear.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("process-stop")
        self.routing_fromline_clear.setIcon(icon)
        self.routing_fromline_clear.setObjectName("routing_fromline_clear")
        self.gridLayout.addWidget(self.routing_fromline_clear, 1, 0, 1, 1)
        self.routing_tab.addTab(self.tab_fromline, "")
        self.verticalLayout_7.addWidget(self.routing_tab)
        self.tabWidget.addTab(self.routing, "")
        self.iso = QtWidgets.QWidget()
        self.iso.setObjectName("iso")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.iso)
        self.verticalLayout.setObjectName("verticalLayout")
        self.iso_travel_group = QtWidgets.QWidget(self.iso)
        self.iso_travel_group.setObjectName("iso_travel_group")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.iso_travel_group)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.iso_travel_label = QtWidgets.QLabel(self.iso_travel_group)
        self.iso_travel_label.setObjectName("iso_travel_label")
        self.horizontalLayout_5.addWidget(self.iso_travel_label)
        self.iso_travel_combo = QtWidgets.QComboBox(self.iso_travel_group)
        self.iso_travel_combo.setObjectName("iso_travel_combo")
        self.horizontalLayout_5.addWidget(self.iso_travel_combo)
        self.verticalLayout.addWidget(self.iso_travel_group)
        self.iso_uni_group = QtWidgets.QWidget(self.iso)
        self.iso_uni_group.setObjectName("iso_uni_group")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.iso_uni_group)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.iso_unit_label = QtWidgets.QLabel(self.iso_uni_group)
        self.iso_unit_label.setEnabled(True)
        self.iso_unit_label.setObjectName("iso_unit_label")
        self.horizontalLayout_6.addWidget(self.iso_unit_label)
        self.iso_unit_combo = QtWidgets.QComboBox(self.iso_uni_group)
        self.iso_unit_combo.setEnabled(True)
        self.iso_unit_combo.setObjectName("iso_unit_combo")
        self.horizontalLayout_6.addWidget(self.iso_unit_combo)
        self.iso_unit_combo.raise_()
        self.iso_unit_label.raise_()
        self.verticalLayout.addWidget(self.iso_uni_group)
        self.iso_range_group = QtWidgets.QWidget(self.iso)
        self.iso_range_group.setObjectName("iso_range_group")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.iso_range_group)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.iso_range_text = QtWidgets.QLineEdit(self.iso_range_group)
        self.iso_range_text.setObjectName("iso_range_text")
        self.gridLayout_3.addWidget(self.iso_range_text, 0, 1, 1, 1)
        self.iso_range_unit_label = QtWidgets.QLabel(self.iso_range_group)
        self.iso_range_unit_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.iso_range_unit_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.iso_range_unit_label.setObjectName("iso_range_unit_label")
        self.gridLayout_3.addWidget(self.iso_range_unit_label, 0, 2, 1, 1)
        self.iso_range_label = QtWidgets.QLabel(self.iso_range_group)
        self.iso_range_label.setObjectName("iso_range_label")
        self.gridLayout_3.addWidget(self.iso_range_label, 0, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 2)
        self.gridLayout_3.setColumnStretch(1, 3)
        self.verticalLayout.addWidget(self.iso_range_group)
        self.iso_location_group = QtWidgets.QWidget(self.iso)
        self.iso_location_group.setObjectName("iso_location_group")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.iso_location_group)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.iso_location_label = QtWidgets.QLabel(self.iso_location_group)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.iso_location_label.setPalette(palette)
        font = QtGui.QFont()
        font.setItalic(True)
        self.iso_location_label.setFont(font)
        self.iso_location_label.setObjectName("iso_location_label")
        self.gridLayout_2.addWidget(self.iso_location_label, 0, 0, 1, 1)
        self.iso_location_button = QtWidgets.QPushButton(self.iso_location_group)
        self.iso_location_button.setObjectName("iso_location_button")
        self.gridLayout_2.addWidget(self.iso_location_button, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.verticalLayout.addWidget(self.iso_location_group)
        self.label_7 = QtWidgets.QLabel(self.iso)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.setStretch(3, 3)
        self.tabWidget.addTab(self.iso, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.debug_text = QtWidgets.QTextBrowser(ORStoolsDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.debug_text.sizePolicy().hasHeightForWidth())
        self.debug_text.setSizePolicy(sizePolicy)
        self.debug_text.setMaximumSize(QtCore.QSize(16777215, 80))
        self.debug_text.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.debug_text.setOpenExternalLinks(True)
        self.debug_text.setObjectName("debug_text")
        self.verticalLayout_5.addWidget(self.debug_text)
        self.widget_2 = QtWidgets.QWidget(ORStoolsDialogBase)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.help_button = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_button.sizePolicy().hasHeightForWidth())
        self.help_button.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("help")
        self.help_button.setIcon(icon)
        self.help_button.setObjectName("help_button")
        self.horizontalLayout_8.addWidget(self.help_button)
        self.label_16 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setOpenExternalLinks(True)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.global_buttons = QtWidgets.QDialogButtonBox(self.widget_2)
        self.global_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.global_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.global_buttons.setObjectName("global_buttons")
        self.horizontalLayout_8.addWidget(self.global_buttons)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.tabWidget.raise_()
        self.widget_4.raise_()
        self.resources_group.raise_()
        self.widget_2.raise_()
        self.debug_text.raise_()

        self.retranslateUi(ORStoolsDialogBase)
        self.tabWidget.setCurrentIndex(0)
        self.routing_tab.setCurrentIndex(0)
        self.global_buttons.accepted.connect(ORStoolsDialogBase.accept)
        self.global_buttons.rejected.connect(ORStoolsDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(ORStoolsDialogBase)
        ORStoolsDialogBase.setTabOrder(self.tabWidget, self.iso_travel_combo)
        ORStoolsDialogBase.setTabOrder(self.iso_travel_combo, self.iso_unit_combo)
        ORStoolsDialogBase.setTabOrder(self.iso_unit_combo, self.iso_location_button)
        ORStoolsDialogBase.setTabOrder(self.iso_location_button, self.iso_unit_combo)
        ORStoolsDialogBase.setTabOrder(self.iso_unit_combo, self.iso_location_button)
        ORStoolsDialogBase.setTabOrder(self.iso_location_button, self.iso_travel_combo)

    def retranslateUi(self, ORStoolsDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ORStoolsDialogBase.setWindowTitle(_translate("ORStoolsDialogBase", "ORS Tools"))
        self.resources_group.setTitle(_translate("ORStoolsDialogBase", "Resources"))
        self.label_3.setText(_translate("ORStoolsDialogBase", "<html><head/><body><p><a href=\"https://openrouteservice.org/dev/#/signup\"><span style=\"font-weight: bold; text-decoration: underline; color:#a8b1f5;\">Sign Up</span></a></p></body></html>"))
        self.label_2.setText(_translate("ORStoolsDialogBase", "<html><head/><body><p><a href=\"https://openrouteservice.org/dev/#/home\"><span style=\"font-weight: bold; text-decoration: underline; color:#a8b1f5;\">Dashboard</span></a></p></body></html>"))
        self.label.setText(_translate("ORStoolsDialogBase", "<html><head/><body><p><a href=\"https://ask.openrouteservice.org/c/sdks\"><span style=\"font-weight: bold; text-decoration: underline; color:#a8b1f5;\">Forum</span></a></p></body></html>"))
        self.label_15.setText(_translate("ORStoolsDialogBase", "Provider"))
        self.quota_text.setText(_translate("ORStoolsDialogBase", "Current quota"))
        self.routing_travel_label.setText(_translate("ORStoolsDialogBase", "Go with"))
        self.routing_travel_combo.setToolTip(_translate("ORStoolsDialogBase", "Mode of travel"))
        self.routing_preference_combo.setToolTip(_translate("ORStoolsDialogBase", "Preference"))
        self.routing_advanced_button.setToolTip(_translate("ORStoolsDialogBase", "Advanced options"))
        self.routing_advanced_button.setText(_translate("ORStoolsDialogBase", "Advanced"))
        self.routing_frompoint_start_group.setTitle(_translate("ORStoolsDialogBase", "Start from"))
        self.routing_frompoint_start_map.setText(_translate("ORStoolsDialogBase", "Map!"))
        self.label_6.setText(_translate("ORStoolsDialogBase", "X"))
        self.label_9.setText(_translate("ORStoolsDialogBase", "Y"))
        self.routing_frompoint_start_clear.setText(_translate("ORStoolsDialogBase", " Clear"))
        self.routing_frompoint_end_group.setTitle(_translate("ORStoolsDialogBase", "End at"))
        self.label_10.setText(_translate("ORStoolsDialogBase", "X"))
        self.routing_frompoint_end_map.setText(_translate("ORStoolsDialogBase", "Map!"))
        self.routing_frompoint_end_clear.setText(_translate("ORStoolsDialogBase", " Clear"))
        self.label_11.setText(_translate("ORStoolsDialogBase", "Y"))
        self.routing_tab.setTabText(self.routing_tab.indexOf(self.tab_frompoint), _translate("ORStoolsDialogBase", "From Point"))
        self.routing_fromline_map.setText(_translate("ORStoolsDialogBase", "Map!"))
        self.routing_fromline_remove.setText(_translate("ORStoolsDialogBase", "<"))
        self.routing_fromline_clear.setText(_translate("ORStoolsDialogBase", " Clear"))
        self.routing_tab.setTabText(self.routing_tab.indexOf(self.tab_fromline), _translate("ORStoolsDialogBase", "From Line"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.routing), _translate("ORStoolsDialogBase", "Routing"))
        self.iso_travel_label.setText(_translate("ORStoolsDialogBase", "Travel mode"))
        self.iso_unit_label.setToolTip(_translate("ORStoolsDialogBase", "<html><head/><body><p>Defaults to \'RecursiveGrid\', \'TIN\' not available yet.</p></body></html>"))
        self.iso_unit_label.setText(_translate("ORStoolsDialogBase", "Dimension"))
        self.iso_unit_combo.setToolTip(_translate("ORStoolsDialogBase", "<html><head/><body><p>Defaults to \'RecursiveGrid\', \'TIN\' not available yet.</p></body></html>"))
        self.iso_range_text.setToolTip(_translate("ORStoolsDialogBase", "Comma separated list of isochrone ranges"))
        self.iso_range_unit_label.setText(_translate("ORStoolsDialogBase", "mins"))
        self.iso_range_label.setToolTip(_translate("ORStoolsDialogBase", "Comma separated list of isochrone ranges"))
        self.iso_range_label.setText(_translate("ORStoolsDialogBase", "Ranges"))
        self.iso_location_label.setToolTip(_translate("ORStoolsDialogBase", "<html><head/><body><p>Will print lat/long, municipality, district and country of mapped location.</p></body></html>"))
        self.iso_location_label.setText(_translate("ORStoolsDialogBase", "Prints location here"))
        self.iso_location_button.setToolTip(_translate("ORStoolsDialogBase", "Click on map canvas to select center point for isochrones"))
        self.iso_location_button.setText(_translate("ORStoolsDialogBase", "Map now!"))
        self.label_7.setText(_translate("ORStoolsDialogBase", "<html>\n"
"<center>\n"
"The layer option has moved to the Processing toolbox\n"
"<br><br>\n"
"<b>Generate Isochrones</b>\n"
"</center>\n"
"</html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.iso), _translate("ORStoolsDialogBase", "Isochrones"))
        self.label_4.setText(_translate("ORStoolsDialogBase", "<html>\n"
"<center>\n"
"This tool has moved to the Processing toolbox\n"
"<br><br>\n"
"<b>Generate Matrix</b>\n"
"</center>\n"
"</html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ORStoolsDialogBase", "Matrix"))
        self.debug_text.setPlaceholderText(_translate("ORStoolsDialogBase", "Queries and errors will be printed here."))
        self.help_button.setText(_translate("ORStoolsDialogBase", "  Help"))
        self.label_16.setText(_translate("ORStoolsDialogBase", "<html><head/><body><p>By <a href=\"https://gis-ops.com\"><img src=\":/plugins/ORStools/img/logo_gisops_300.png\" width=100/></a></p></body></html>"))

from qgsfilterlineedit import QgsFilterLineEdit
from . import resources_rc
