# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/OSMtoolsDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OSMtoolsDialogBase(object):
    def setupUi(self, OSMtoolsDialogBase):
        OSMtoolsDialogBase.setObjectName("OSMtoolsDialogBase")
        OSMtoolsDialogBase.resize(402, 687)
        OSMtoolsDialogBase.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(OSMtoolsDialogBase)
        self.gridLayout.setObjectName("gridLayout")
        self.global_buttons = QtWidgets.QDialogButtonBox(OSMtoolsDialogBase)
        self.global_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.global_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.global_buttons.setObjectName("global_buttons")
        self.gridLayout.addWidget(self.global_buttons, 6, 0, 1, 2)
        self.key_group = QtWidgets.QGroupBox(OSMtoolsDialogBase)
        self.key_group.setObjectName("key_group")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.key_group)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.key_text = QtWidgets.QLineEdit(self.key_group)
        self.key_text.setObjectName("key_text")
        self.horizontalLayout_4.addWidget(self.key_text)
        self.key_link = QtWidgets.QLabel(self.key_group)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.key_link.setFont(font)
        self.key_link.setOpenExternalLinks(True)
        self.key_link.setObjectName("key_link")
        self.horizontalLayout_4.addWidget(self.key_link)
        self.gridLayout.addWidget(self.key_group, 3, 0, 1, 1)
        self.header_text = QtWidgets.QLabel(OSMtoolsDialogBase)
        self.header_text.setAlignment(QtCore.Qt.AlignCenter)
        self.header_text.setOpenExternalLinks(True)
        self.header_text.setObjectName("header_text")
        self.gridLayout.addWidget(self.header_text, 2, 0, 1, 1)
        self.header_pic = QtWidgets.QLabel(OSMtoolsDialogBase)
        self.header_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.header_pic.setObjectName("header_pic")
        self.gridLayout.addWidget(self.header_pic, 0, 0, 1, 1)
        self.header_subpic = QtWidgets.QLabel(OSMtoolsDialogBase)
        self.header_subpic.setAlignment(QtCore.Qt.AlignCenter)
        self.header_subpic.setOpenExternalLinks(True)
        self.header_subpic.setObjectName("header_subpic")
        self.gridLayout.addWidget(self.header_subpic, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(OSMtoolsDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.routing = QtWidgets.QWidget()
        self.routing.setObjectName("routing")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.routing)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.routing_scrollarea = QtWidgets.QScrollArea(self.routing)
        self.routing_scrollarea.setWidgetResizable(True)
        self.routing_scrollarea.setObjectName("routing_scrollarea")
        self.routing_scrollarea_contents = QtWidgets.QWidget()
        self.routing_scrollarea_contents.setGeometry(QtCore.QRect(0, 0, 340, 907))
        self.routing_scrollarea_contents.setObjectName("routing_scrollarea_contents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.routing_scrollarea_contents)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.routing_via_group = QtWidgets.QGroupBox(self.routing_scrollarea_contents)
        self.routing_via_group.setObjectName("routing_via_group")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.routing_via_group)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.routing_via_label = QtWidgets.QLabel(self.routing_via_group)
        font = QtGui.QFont()
        font.setItalic(False)
        self.routing_via_label.setFont(font)
        self.routing_via_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.routing_via_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.routing_via_label.setObjectName("routing_via_label")
        self.horizontalLayout.addWidget(self.routing_via_label)
        self.routing_via_map_button = QtWidgets.QPushButton(self.routing_via_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_via_map_button.sizePolicy().hasHeightForWidth())
        self.routing_via_map_button.setSizePolicy(sizePolicy)
        self.routing_via_map_button.setObjectName("routing_via_map_button")
        self.horizontalLayout.addWidget(self.routing_via_map_button)
        self.routing_via_clear_button = QtWidgets.QPushButton(self.routing_via_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.routing_via_clear_button.sizePolicy().hasHeightForWidth())
        self.routing_via_clear_button.setSizePolicy(sizePolicy)
        self.routing_via_clear_button.setObjectName("routing_via_clear_button")
        self.horizontalLayout.addWidget(self.routing_via_clear_button)
        self.horizontalLayout.setStretch(0, 10)
        self.gridLayout_8.addWidget(self.routing_via_group, 7, 0, 1, 1)
        self.routing_start_group = QtWidgets.QGroupBox(self.routing_scrollarea_contents)
        self.routing_start_group.setAlignment(QtCore.Qt.AlignCenter)
        self.routing_start_group.setObjectName("routing_start_group")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.routing_start_group)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.routing_start_frommap_group = QtWidgets.QWidget(self.routing_start_group)
        self.routing_start_frommap_group.setObjectName("routing_start_frommap_group")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.routing_start_frommap_group)
        self.gridLayout_10.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.routing_start_frommap_radio = QtWidgets.QRadioButton(self.routing_start_frommap_group)
        self.routing_start_frommap_radio.setChecked(True)
        self.routing_start_frommap_radio.setObjectName("routing_start_frommap_radio")
        self.start_buttongroup = QtWidgets.QButtonGroup(OSMtoolsDialogBase)
        self.start_buttongroup.setObjectName("start_buttongroup")
        self.start_buttongroup.addButton(self.routing_start_frommap_radio)
        self.gridLayout_10.addWidget(self.routing_start_frommap_radio, 0, 0, 1, 1)
        self.routing_start_frommap_label = QtWidgets.QLabel(self.routing_start_frommap_group)
        font = QtGui.QFont()
        font.setItalic(True)
        self.routing_start_frommap_label.setFont(font)
        self.routing_start_frommap_label.setObjectName("routing_start_frommap_label")
        self.gridLayout_10.addWidget(self.routing_start_frommap_label, 1, 0, 1, 1)
        self.routing_start_frommap_button = QtWidgets.QPushButton(self.routing_start_frommap_group)
        self.routing_start_frommap_button.setObjectName("routing_start_frommap_button")
        self.gridLayout_10.addWidget(self.routing_start_frommap_button, 1, 1, 1, 1)
        self.gridLayout_10.setColumnStretch(0, 1)
        self.gridLayout_4.addWidget(self.routing_start_frommap_group, 0, 0, 1, 1)
        self.routing_start_fromlayer_group = QtWidgets.QWidget(self.routing_start_group)
        self.routing_start_fromlayer_group.setObjectName("routing_start_fromlayer_group")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.routing_start_fromlayer_group)
        self.gridLayout_11.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.routing_start_fromlayer_radio = QtWidgets.QRadioButton(self.routing_start_fromlayer_group)
        self.routing_start_fromlayer_radio.setChecked(False)
        self.routing_start_fromlayer_radio.setObjectName("routing_start_fromlayer_radio")
        self.start_buttongroup.addButton(self.routing_start_fromlayer_radio)
        self.gridLayout_11.addWidget(self.routing_start_fromlayer_radio, 0, 0, 1, 1)
        self.routing_start_fromlayer_combo = QtWidgets.QComboBox(self.routing_start_fromlayer_group)
        self.routing_start_fromlayer_combo.setEnabled(False)
        self.routing_start_fromlayer_combo.setWhatsThis("")
        self.routing_start_fromlayer_combo.setObjectName("routing_start_fromlayer_combo")
        self.gridLayout_11.addWidget(self.routing_start_fromlayer_combo, 1, 0, 1, 1)
        self.routing_start_fromlayer_refresh = QtWidgets.QPushButton(self.routing_start_fromlayer_group)
        self.routing_start_fromlayer_refresh.setEnabled(False)
        self.routing_start_fromlayer_refresh.setObjectName("routing_start_fromlayer_refresh")
        self.gridLayout_11.addWidget(self.routing_start_fromlayer_refresh, 1, 1, 1, 1)
        self.routing_start_fromlayer_id_label = QtWidgets.QLabel(self.routing_start_fromlayer_group)
        self.routing_start_fromlayer_id_label.setObjectName("routing_start_fromlayer_id_label")
        self.gridLayout_11.addWidget(self.routing_start_fromlayer_id_label, 2, 0, 1, 2)
        self.routing_start_fromlayer_id_combo = QtWidgets.QComboBox(self.routing_start_fromlayer_group)
        self.routing_start_fromlayer_id_combo.setEnabled(False)
        self.routing_start_fromlayer_id_combo.setObjectName("routing_start_fromlayer_id_combo")
        self.gridLayout_11.addWidget(self.routing_start_fromlayer_id_combo, 3, 0, 1, 2)
        self.gridLayout_11.setColumnStretch(0, 1)
        self.gridLayout_4.addWidget(self.routing_start_fromlayer_group, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.routing_start_group, 2, 0, 1, 1)
        self.routing_twolayer_group = QtWidgets.QGroupBox(self.routing_scrollarea_contents)
        self.routing_twolayer_group.setObjectName("routing_twolayer_group")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.routing_twolayer_group)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.routing_twolayer_rowbyrow = QtWidgets.QRadioButton(self.routing_twolayer_group)
        self.routing_twolayer_rowbyrow.setEnabled(False)
        self.routing_twolayer_rowbyrow.setChecked(True)
        self.routing_twolayer_rowbyrow.setObjectName("routing_twolayer_rowbyrow")
        self.gridLayout_6.addWidget(self.routing_twolayer_rowbyrow, 0, 0, 1, 1)
        self.routing_twolayer_allbyall = QtWidgets.QRadioButton(self.routing_twolayer_group)
        self.routing_twolayer_allbyall.setEnabled(False)
        self.routing_twolayer_allbyall.setObjectName("routing_twolayer_allbyall")
        self.gridLayout_6.addWidget(self.routing_twolayer_allbyall, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.routing_twolayer_group, 6, 0, 1, 1)
        self.routing_end_group = QtWidgets.QGroupBox(self.routing_scrollarea_contents)
        self.routing_end_group.setAlignment(QtCore.Qt.AlignCenter)
        self.routing_end_group.setObjectName("routing_end_group")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.routing_end_group)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.routing_end_fromlayer_group = QtWidgets.QWidget(self.routing_end_group)
        self.routing_end_fromlayer_group.setObjectName("routing_end_fromlayer_group")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.routing_end_fromlayer_group)
        self.gridLayout_13.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.routing_end_fromlayer_radio = QtWidgets.QRadioButton(self.routing_end_fromlayer_group)
        self.routing_end_fromlayer_radio.setEnabled(True)
        self.routing_end_fromlayer_radio.setChecked(False)
        self.routing_end_fromlayer_radio.setObjectName("routing_end_fromlayer_radio")
        self.end_buttongroup = QtWidgets.QButtonGroup(OSMtoolsDialogBase)
        self.end_buttongroup.setObjectName("end_buttongroup")
        self.end_buttongroup.addButton(self.routing_end_fromlayer_radio)
        self.gridLayout_13.addWidget(self.routing_end_fromlayer_radio, 0, 0, 1, 1)
        self.routing_end_fromlayer_combo = QtWidgets.QComboBox(self.routing_end_fromlayer_group)
        self.routing_end_fromlayer_combo.setEnabled(False)
        self.routing_end_fromlayer_combo.setWhatsThis("")
        self.routing_end_fromlayer_combo.setObjectName("routing_end_fromlayer_combo")
        self.gridLayout_13.addWidget(self.routing_end_fromlayer_combo, 1, 0, 1, 1)
        self.routing_end_fromlayer_refresh = QtWidgets.QPushButton(self.routing_end_fromlayer_group)
        self.routing_end_fromlayer_refresh.setEnabled(False)
        self.routing_end_fromlayer_refresh.setObjectName("routing_end_fromlayer_refresh")
        self.gridLayout_13.addWidget(self.routing_end_fromlayer_refresh, 1, 1, 1, 1)
        self.routing_end_fromlayer_id_label = QtWidgets.QLabel(self.routing_end_fromlayer_group)
        self.routing_end_fromlayer_id_label.setObjectName("routing_end_fromlayer_id_label")
        self.gridLayout_13.addWidget(self.routing_end_fromlayer_id_label, 2, 0, 1, 2)
        self.routing_end_fromlayer_id_combo = QtWidgets.QComboBox(self.routing_end_fromlayer_group)
        self.routing_end_fromlayer_id_combo.setEnabled(False)
        self.routing_end_fromlayer_id_combo.setObjectName("routing_end_fromlayer_id_combo")
        self.gridLayout_13.addWidget(self.routing_end_fromlayer_id_combo, 3, 0, 1, 2)
        self.gridLayout_13.setColumnStretch(0, 1)
        self.gridLayout_5.addWidget(self.routing_end_fromlayer_group, 1, 0, 1, 1)
        self.routing_end_frommap_group = QtWidgets.QWidget(self.routing_end_group)
        self.routing_end_frommap_group.setObjectName("routing_end_frommap_group")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.routing_end_frommap_group)
        self.gridLayout_12.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.routing_end_frommap_radio = QtWidgets.QRadioButton(self.routing_end_frommap_group)
        self.routing_end_frommap_radio.setChecked(True)
        self.routing_end_frommap_radio.setObjectName("routing_end_frommap_radio")
        self.end_buttongroup.addButton(self.routing_end_frommap_radio)
        self.gridLayout_12.addWidget(self.routing_end_frommap_radio, 0, 0, 1, 1)
        self.routing_end_frommap_label = QtWidgets.QLabel(self.routing_end_frommap_group)
        font = QtGui.QFont()
        font.setItalic(True)
        self.routing_end_frommap_label.setFont(font)
        self.routing_end_frommap_label.setObjectName("routing_end_frommap_label")
        self.gridLayout_12.addWidget(self.routing_end_frommap_label, 1, 0, 1, 1)
        self.routing_end_frommap_button = QtWidgets.QPushButton(self.routing_end_frommap_group)
        self.routing_end_frommap_button.setObjectName("routing_end_frommap_button")
        self.gridLayout_12.addWidget(self.routing_end_frommap_button, 1, 1, 1, 1)
        self.gridLayout_12.setColumnStretch(0, 1)
        self.gridLayout_5.addWidget(self.routing_end_frommap_group, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.routing_end_group, 5, 0, 1, 1)
        self.routing_travel_group = QtWidgets.QWidget(self.routing_scrollarea_contents)
        self.routing_travel_group.setObjectName("routing_travel_group")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.routing_travel_group)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.routing_travel_label = QtWidgets.QLabel(self.routing_travel_group)
        self.routing_travel_label.setObjectName("routing_travel_label")
        self.horizontalLayout_2.addWidget(self.routing_travel_label)
        self.routing_travel_combo = QtWidgets.QComboBox(self.routing_travel_group)
        self.routing_travel_combo.setObjectName("routing_travel_combo")
        self.horizontalLayout_2.addWidget(self.routing_travel_combo)
        self.gridLayout_8.addWidget(self.routing_travel_group, 0, 0, 1, 1)
        self.routing_preference_group = QtWidgets.QWidget(self.routing_scrollarea_contents)
        self.routing_preference_group.setObjectName("routing_preference_group")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.routing_preference_group)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.routing_preference_lable = QtWidgets.QLabel(self.routing_preference_group)
        self.routing_preference_lable.setObjectName("routing_preference_lable")
        self.horizontalLayout_3.addWidget(self.routing_preference_lable)
        self.routing_preference_combo = QtWidgets.QComboBox(self.routing_preference_group)
        self.routing_preference_combo.setObjectName("routing_preference_combo")
        self.horizontalLayout_3.addWidget(self.routing_preference_combo)
        self.gridLayout_8.addWidget(self.routing_preference_group, 1, 0, 1, 1)
        self.routing_avoid_group = QtWidgets.QGroupBox(self.routing_scrollarea_contents)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.routing_avoid_group.setFont(font)
        self.routing_avoid_group.setObjectName("routing_avoid_group")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.routing_avoid_group)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.routing_avoid_highways = QtWidgets.QCheckBox(self.routing_avoid_group)
        self.routing_avoid_highways.setObjectName("routing_avoid_highways")
        self.gridLayout_9.addWidget(self.routing_avoid_highways, 0, 0, 1, 1)
        self.routing_avoid_toll = QtWidgets.QCheckBox(self.routing_avoid_group)
        self.routing_avoid_toll.setObjectName("routing_avoid_toll")
        self.gridLayout_9.addWidget(self.routing_avoid_toll, 0, 1, 1, 1)
        self.routing_avoid_tunnels = QtWidgets.QCheckBox(self.routing_avoid_group)
        self.routing_avoid_tunnels.setObjectName("routing_avoid_tunnels")
        self.gridLayout_9.addWidget(self.routing_avoid_tunnels, 1, 0, 1, 1)
        self.routing_avoid_ferries = QtWidgets.QCheckBox(self.routing_avoid_group)
        self.routing_avoid_ferries.setObjectName("routing_avoid_ferries")
        self.gridLayout_9.addWidget(self.routing_avoid_ferries, 1, 1, 1, 1)
        self.routing_avoid_fords = QtWidgets.QCheckBox(self.routing_avoid_group)
        self.routing_avoid_fords.setObjectName("routing_avoid_fords")
        self.gridLayout_9.addWidget(self.routing_avoid_fords, 2, 0, 1, 1)
        self.routing_avoid_paved = QtWidgets.QCheckBox(self.routing_avoid_group)
        self.routing_avoid_paved.setObjectName("routing_avoid_paved")
        self.gridLayout_9.addWidget(self.routing_avoid_paved, 3, 0, 1, 1)
        self.routing_avoid_tracks = QtWidgets.QCheckBox(self.routing_avoid_group)
        self.routing_avoid_tracks.setObjectName("routing_avoid_tracks")
        self.gridLayout_9.addWidget(self.routing_avoid_tracks, 2, 1, 1, 1)
        self.routing_avoid_unpaved = QtWidgets.QCheckBox(self.routing_avoid_group)
        self.routing_avoid_unpaved.setObjectName("routing_avoid_unpaved")
        self.gridLayout_9.addWidget(self.routing_avoid_unpaved, 3, 1, 1, 1)
        self.gridLayout_8.addWidget(self.routing_avoid_group, 8, 0, 1, 1)
        self.routing_scrollarea.setWidget(self.routing_scrollarea_contents)
        self.verticalLayout_2.addWidget(self.routing_scrollarea)
        self.tabWidget.addTab(self.routing, "")
        self.iso = QtWidgets.QWidget()
        self.iso.setObjectName("iso")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.iso)
        self.verticalLayout.setObjectName("verticalLayout")
        self.iso_travel_group = QtWidgets.QWidget(self.iso)
        self.iso_travel_group.setObjectName("iso_travel_group")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.iso_travel_group)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.iso_travel_label = QtWidgets.QLabel(self.iso_travel_group)
        self.iso_travel_label.setObjectName("iso_travel_label")
        self.horizontalLayout_5.addWidget(self.iso_travel_label)
        self.iso_travel_combo = QtWidgets.QComboBox(self.iso_travel_group)
        self.iso_travel_combo.setObjectName("iso_travel_combo")
        self.horizontalLayout_5.addWidget(self.iso_travel_combo)
        self.verticalLayout.addWidget(self.iso_travel_group)
        self.iso_uni_group = QtWidgets.QWidget(self.iso)
        self.iso_uni_group.setObjectName("iso_uni_group")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.iso_uni_group)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.iso_unit_label = QtWidgets.QLabel(self.iso_uni_group)
        self.iso_unit_label.setEnabled(True)
        self.iso_unit_label.setObjectName("iso_unit_label")
        self.horizontalLayout_6.addWidget(self.iso_unit_label)
        self.iso_unit_combo = QtWidgets.QComboBox(self.iso_uni_group)
        self.iso_unit_combo.setEnabled(True)
        self.iso_unit_combo.setObjectName("iso_unit_combo")
        self.horizontalLayout_6.addWidget(self.iso_unit_combo)
        self.iso_unit_combo.raise_()
        self.iso_unit_label.raise_()
        self.verticalLayout.addWidget(self.iso_uni_group)
        self.iso_range_group = QtWidgets.QWidget(self.iso)
        self.iso_range_group.setObjectName("iso_range_group")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.iso_range_group)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.iso_range_text = QtWidgets.QLineEdit(self.iso_range_group)
        self.iso_range_text.setObjectName("iso_range_text")
        self.gridLayout_3.addWidget(self.iso_range_text, 0, 1, 1, 1)
        self.iso_range_unit_label = QtWidgets.QLabel(self.iso_range_group)
        self.iso_range_unit_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.iso_range_unit_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.iso_range_unit_label.setObjectName("iso_range_unit_label")
        self.gridLayout_3.addWidget(self.iso_range_unit_label, 0, 2, 1, 1)
        self.iso_range_label = QtWidgets.QLabel(self.iso_range_group)
        self.iso_range_label.setObjectName("iso_range_label")
        self.gridLayout_3.addWidget(self.iso_range_label, 0, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 10)
        self.gridLayout_3.setColumnStretch(1, 15)
        self.verticalLayout.addWidget(self.iso_range_group)
        self.widget_7 = QtWidgets.QWidget(self.iso)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout.addWidget(self.widget_7)
        self.iso_location_group = QtWidgets.QWidget(self.iso)
        self.iso_location_group.setObjectName("iso_location_group")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.iso_location_group)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.iso_location_label = QtWidgets.QLabel(self.iso_location_group)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.iso_location_label.setPalette(palette)
        font = QtGui.QFont()
        font.setItalic(True)
        self.iso_location_label.setFont(font)
        self.iso_location_label.setObjectName("iso_location_label")
        self.gridLayout_2.addWidget(self.iso_location_label, 0, 0, 1, 1)
        self.iso_location_button = QtWidgets.QPushButton(self.iso_location_group)
        self.iso_location_button.setObjectName("iso_location_button")
        self.gridLayout_2.addWidget(self.iso_location_button, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.verticalLayout.addWidget(self.iso_location_group)
        self.iso_layer_group = QtWidgets.QWidget(self.iso)
        self.iso_layer_group.setObjectName("iso_layer_group")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.iso_layer_group)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.iso_layer_refresh = QtWidgets.QPushButton(self.iso_layer_group)
        self.iso_layer_refresh.setEnabled(False)
        self.iso_layer_refresh.setObjectName("iso_layer_refresh")
        self.gridLayout_14.addWidget(self.iso_layer_refresh, 3, 2, 1, 1)
        self.iso_layer_label = QtWidgets.QLabel(self.iso_layer_group)
        self.iso_layer_label.setEnabled(False)
        self.iso_layer_label.setObjectName("iso_layer_label")
        self.gridLayout_14.addWidget(self.iso_layer_label, 1, 0, 1, 2)
        self.iso_layer_combo = QtWidgets.QComboBox(self.iso_layer_group)
        self.iso_layer_combo.setEnabled(False)
        self.iso_layer_combo.setWhatsThis("")
        self.iso_layer_combo.setEditable(False)
        self.iso_layer_combo.setObjectName("iso_layer_combo")
        self.gridLayout_14.addWidget(self.iso_layer_combo, 3, 0, 1, 2)
        self.iso_layer_check = QtWidgets.QCheckBox(self.iso_layer_group)
        self.iso_layer_check.setObjectName("iso_layer_check")
        self.gridLayout_14.addWidget(self.iso_layer_check, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.iso_layer_group)
        self.verticalLayout.setStretch(4, 3)
        self.tabWidget.addTab(self.iso, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.matrix_travel_group = QtWidgets.QWidget(self.tab_2)
        self.matrix_travel_group.setObjectName("matrix_travel_group")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.matrix_travel_group)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.matrix_travel_combo = QtWidgets.QComboBox(self.matrix_travel_group)
        self.matrix_travel_combo.setObjectName("matrix_travel_combo")
        self.gridLayout_15.addWidget(self.matrix_travel_combo, 0, 1, 1, 1)
        self.matrix_travel_label = QtWidgets.QLabel(self.matrix_travel_group)
        self.matrix_travel_label.setObjectName("matrix_travel_label")
        self.gridLayout_15.addWidget(self.matrix_travel_label, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.matrix_travel_group)
        self.matrix_start_group = QtWidgets.QWidget(self.tab_2)
        self.matrix_start_group.setObjectName("matrix_start_group")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.matrix_start_group)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.matrix_start_refresh = QtWidgets.QPushButton(self.matrix_start_group)
        self.matrix_start_refresh.setEnabled(True)
        self.matrix_start_refresh.setObjectName("matrix_start_refresh")
        self.gridLayout_16.addWidget(self.matrix_start_refresh, 1, 1, 1, 1)
        self.matrix_start_id_combo = QtWidgets.QComboBox(self.matrix_start_group)
        self.matrix_start_id_combo.setEnabled(True)
        self.matrix_start_id_combo.setObjectName("matrix_start_id_combo")
        self.gridLayout_16.addWidget(self.matrix_start_id_combo, 3, 0, 1, 2)
        self.matrix_start_combo = QtWidgets.QComboBox(self.matrix_start_group)
        self.matrix_start_combo.setEnabled(True)
        self.matrix_start_combo.setWhatsThis("")
        self.matrix_start_combo.setObjectName("matrix_start_combo")
        self.gridLayout_16.addWidget(self.matrix_start_combo, 1, 0, 1, 1)
        self.matrix_start_id_label = QtWidgets.QLabel(self.matrix_start_group)
        self.matrix_start_id_label.setObjectName("matrix_start_id_label")
        self.gridLayout_16.addWidget(self.matrix_start_id_label, 2, 0, 1, 2)
        self.matrix_start_label = QtWidgets.QLabel(self.matrix_start_group)
        self.matrix_start_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.matrix_start_label.setObjectName("matrix_start_label")
        self.gridLayout_16.addWidget(self.matrix_start_label, 0, 0, 1, 2)
        self.gridLayout_16.setColumnStretch(0, 1)
        self.verticalLayout_3.addWidget(self.matrix_start_group)
        self.matrix_end_group = QtWidgets.QWidget(self.tab_2)
        self.matrix_end_group.setObjectName("matrix_end_group")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.matrix_end_group)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.matrix_end_combo = QtWidgets.QComboBox(self.matrix_end_group)
        self.matrix_end_combo.setEnabled(True)
        self.matrix_end_combo.setWhatsThis("")
        self.matrix_end_combo.setObjectName("matrix_end_combo")
        self.gridLayout_17.addWidget(self.matrix_end_combo, 1, 0, 1, 1)
        self.matrix_end_refresh = QtWidgets.QPushButton(self.matrix_end_group)
        self.matrix_end_refresh.setEnabled(True)
        self.matrix_end_refresh.setObjectName("matrix_end_refresh")
        self.gridLayout_17.addWidget(self.matrix_end_refresh, 1, 1, 1, 1)
        self.matrix_end_id_label = QtWidgets.QLabel(self.matrix_end_group)
        self.matrix_end_id_label.setObjectName("matrix_end_id_label")
        self.gridLayout_17.addWidget(self.matrix_end_id_label, 2, 0, 1, 2)
        self.matrix_end_id_combo = QtWidgets.QComboBox(self.matrix_end_group)
        self.matrix_end_id_combo.setEnabled(True)
        self.matrix_end_id_combo.setObjectName("matrix_end_id_combo")
        self.gridLayout_17.addWidget(self.matrix_end_id_combo, 3, 0, 1, 2)
        self.matrix_end_label = QtWidgets.QLabel(self.matrix_end_group)
        self.matrix_end_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.matrix_end_label.setObjectName("matrix_end_label")
        self.gridLayout_17.addWidget(self.matrix_end_label, 0, 0, 1, 2)
        self.gridLayout_17.setColumnStretch(0, 1)
        self.verticalLayout_3.addWidget(self.matrix_end_group)
        self.matrix_placeholder = QtWidgets.QWidget(self.tab_2)
        self.matrix_placeholder.setObjectName("matrix_placeholder")
        self.verticalLayout_3.addWidget(self.matrix_placeholder)
        self.verticalLayout_3.setStretch(3, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 5, 0, 1, 1)
        self.global_buttons.raise_()
        self.tabWidget.raise_()
        self.key_group.raise_()
        self.header_pic.raise_()
        self.header_text.raise_()
        self.header_subpic.raise_()

        self.retranslateUi(OSMtoolsDialogBase)
        self.tabWidget.setCurrentIndex(0)
        self.global_buttons.accepted.connect(OSMtoolsDialogBase.accept)
        self.global_buttons.rejected.connect(OSMtoolsDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(OSMtoolsDialogBase)
        OSMtoolsDialogBase.setTabOrder(self.key_text, self.tabWidget)
        OSMtoolsDialogBase.setTabOrder(self.tabWidget, self.routing_scrollarea)
        OSMtoolsDialogBase.setTabOrder(self.routing_scrollarea, self.routing_start_frommap_radio)
        OSMtoolsDialogBase.setTabOrder(self.routing_start_frommap_radio, self.routing_start_frommap_button)
        OSMtoolsDialogBase.setTabOrder(self.routing_start_frommap_button, self.routing_start_fromlayer_radio)
        OSMtoolsDialogBase.setTabOrder(self.routing_start_fromlayer_radio, self.global_buttons)
        OSMtoolsDialogBase.setTabOrder(self.global_buttons, self.routing_twolayer_rowbyrow)
        OSMtoolsDialogBase.setTabOrder(self.routing_twolayer_rowbyrow, self.routing_twolayer_allbyall)
        OSMtoolsDialogBase.setTabOrder(self.routing_twolayer_allbyall, self.iso_travel_combo)
        OSMtoolsDialogBase.setTabOrder(self.iso_travel_combo, self.iso_unit_combo)
        OSMtoolsDialogBase.setTabOrder(self.iso_unit_combo, self.iso_location_button)
        OSMtoolsDialogBase.setTabOrder(self.iso_location_button, self.routing_preference_combo)
        OSMtoolsDialogBase.setTabOrder(self.routing_preference_combo, self.iso_unit_combo)
        OSMtoolsDialogBase.setTabOrder(self.iso_unit_combo, self.iso_location_button)
        OSMtoolsDialogBase.setTabOrder(self.iso_location_button, self.routing_via_map_button)
        OSMtoolsDialogBase.setTabOrder(self.routing_via_map_button, self.iso_travel_combo)
        OSMtoolsDialogBase.setTabOrder(self.iso_travel_combo, self.iso_layer_combo)
        OSMtoolsDialogBase.setTabOrder(self.iso_layer_combo, self.routing_travel_combo)
        OSMtoolsDialogBase.setTabOrder(self.routing_travel_combo, self.routing_start_fromlayer_combo)
        OSMtoolsDialogBase.setTabOrder(self.routing_start_fromlayer_combo, self.routing_end_frommap_radio)
        OSMtoolsDialogBase.setTabOrder(self.routing_end_frommap_radio, self.routing_end_frommap_button)
        OSMtoolsDialogBase.setTabOrder(self.routing_end_frommap_button, self.routing_end_fromlayer_radio)
        OSMtoolsDialogBase.setTabOrder(self.routing_end_fromlayer_radio, self.routing_end_fromlayer_combo)
        OSMtoolsDialogBase.setTabOrder(self.routing_end_fromlayer_combo, self.routing_end_fromlayer_id_combo)
        OSMtoolsDialogBase.setTabOrder(self.routing_end_fromlayer_id_combo, self.routing_twolayer_rowbyrow)
        OSMtoolsDialogBase.setTabOrder(self.routing_twolayer_rowbyrow, self.routing_twolayer_allbyall)
        OSMtoolsDialogBase.setTabOrder(self.routing_twolayer_allbyall, self.routing_via_map_button)
        OSMtoolsDialogBase.setTabOrder(self.routing_via_map_button, self.routing_via_clear_button)
        OSMtoolsDialogBase.setTabOrder(self.routing_via_clear_button, self.routing_travel_combo)
        OSMtoolsDialogBase.setTabOrder(self.routing_travel_combo, self.routing_preference_combo)
        OSMtoolsDialogBase.setTabOrder(self.routing_preference_combo, self.routing_start_fromlayer_id_combo)
        OSMtoolsDialogBase.setTabOrder(self.routing_start_fromlayer_id_combo, self.routing_via_clear_button)

    def retranslateUi(self, OSMtoolsDialogBase):
        _translate = QtCore.QCoreApplication.translate
        OSMtoolsDialogBase.setWindowTitle(_translate("OSMtoolsDialogBase", "OSM Tools"))
        self.key_group.setTitle(_translate("OSMtoolsDialogBase", "API key"))
        self.key_text.setToolTip(_translate("OSMtoolsDialogBase", "<html><head/><body><p>Get your personal API key!</p><p>2500 requests/day and 40 requests/minute limitations</p></body></html>"))
        self.key_link.setToolTip(_translate("OSMtoolsDialogBase", "<html><head/><body><p>Register for access to ORS</p></body></html>"))
        self.key_link.setText(_translate("OSMtoolsDialogBase", "<a href=\"https://openrouteservice.org/sign-up/\" style=\"font-size: 14px; color: #b5152b\">Order Key!</a>"))
        self.header_text.setText(_translate("OSMtoolsDialogBase", "<html><head/><body><p><a href=\"https://openrouteservice.org/\"><span style=\" text-decoration: underline; color:#b5152b;\">openrouteservice.org</span></a> | by <a href=\"mailto:nils@openrouteservice.org\"><span style=\" text-decoration: underline; color:#b5152b;\">Nils Nolde</span></a></p></body></html>"))
        self.header_pic.setText(_translate("OSMtoolsDialogBase", "TextLabel"))
        self.header_subpic.setText(_translate("OSMtoolsDialogBase", "<a href=\"https://github.com/GIScience/openrouteservice\" style=\"color: black; text-decoration: none\">We truly <span style=\"color: #b5152b\">♥</span> Open Source.</a>"))
        self.routing_via_group.setTitle(_translate("OSMtoolsDialogBase", "Via"))
        self.routing_via_label.setText(_translate("OSMtoolsDialogBase", "Long,Lat"))
        self.routing_via_map_button.setText(_translate("OSMtoolsDialogBase", "Map"))
        self.routing_via_clear_button.setText(_translate("OSMtoolsDialogBase", "Clear"))
        self.routing_start_group.setTitle(_translate("OSMtoolsDialogBase", "Start Location(s)"))
        self.routing_start_frommap_radio.setText(_translate("OSMtoolsDialogBase", "From Map"))
        self.routing_start_frommap_label.setText(_translate("OSMtoolsDialogBase", "Long,Lat"))
        self.routing_start_frommap_button.setText(_translate("OSMtoolsDialogBase", "Map Coordinates"))
        self.routing_start_fromlayer_radio.setText(_translate("OSMtoolsDialogBase", "From Layer"))
        self.routing_start_fromlayer_combo.setToolTip(_translate("OSMtoolsDialogBase", "Input Layer must be of type \'Point\' "))
        self.routing_start_fromlayer_refresh.setText(_translate("OSMtoolsDialogBase", "Refresh List"))
        self.routing_start_fromlayer_id_label.setText(_translate("OSMtoolsDialogBase", "Select Unique ID field"))
        self.routing_twolayer_group.setTitle(_translate("OSMtoolsDialogBase", "Two layer mode"))
        self.routing_twolayer_rowbyrow.setToolTip(_translate("OSMtoolsDialogBase", "<html><head/><body><p>start_layer[1]--&gt;end_layer[1]</p><p>start_layer[2]--&gt;end_layer[2]<br/></p></body></html>"))
        self.routing_twolayer_rowbyrow.setText(_translate("OSMtoolsDialogBase", "Row by row"))
        self.routing_twolayer_allbyall.setToolTip(_translate("OSMtoolsDialogBase", "<html><head/><body><p>start_layer[1]--&gt;end_layer[1]</p><p>start_layer[1]--&gt;end_layer[2]</p><p>start_layer[2]--&gt;end_layer[1]</p><p>start_layer[2]--&gt;end_layer[2]<br/></p></body></html>"))
        self.routing_twolayer_allbyall.setText(_translate("OSMtoolsDialogBase", "All rows by all rows"))
        self.routing_end_group.setTitle(_translate("OSMtoolsDialogBase", "End Location(s)"))
        self.routing_end_fromlayer_radio.setText(_translate("OSMtoolsDialogBase", "From Layer"))
        self.routing_end_fromlayer_combo.setToolTip(_translate("OSMtoolsDialogBase", "Input Layer must be of type \'Point\' and in EPSG:4326"))
        self.routing_end_fromlayer_refresh.setText(_translate("OSMtoolsDialogBase", "Refresh List"))
        self.routing_end_fromlayer_id_label.setText(_translate("OSMtoolsDialogBase", "Select Unique ID field"))
        self.routing_end_frommap_radio.setText(_translate("OSMtoolsDialogBase", "From Map"))
        self.routing_end_frommap_label.setText(_translate("OSMtoolsDialogBase", "Long,Lat"))
        self.routing_end_frommap_button.setText(_translate("OSMtoolsDialogBase", "Map Coordinates"))
        self.routing_travel_label.setText(_translate("OSMtoolsDialogBase", "Travel mode"))
        self.routing_preference_lable.setText(_translate("OSMtoolsDialogBase", "Preference"))
        self.routing_avoid_group.setTitle(_translate("OSMtoolsDialogBase", "Avoid features"))
        self.routing_avoid_highways.setText(_translate("OSMtoolsDialogBase", "highways"))
        self.routing_avoid_toll.setText(_translate("OSMtoolsDialogBase", "tollways"))
        self.routing_avoid_tunnels.setText(_translate("OSMtoolsDialogBase", "tunnels"))
        self.routing_avoid_ferries.setText(_translate("OSMtoolsDialogBase", "ferries"))
        self.routing_avoid_fords.setText(_translate("OSMtoolsDialogBase", "fords"))
        self.routing_avoid_paved.setText(_translate("OSMtoolsDialogBase", "pavedroads"))
        self.routing_avoid_tracks.setText(_translate("OSMtoolsDialogBase", "tracks"))
        self.routing_avoid_unpaved.setText(_translate("OSMtoolsDialogBase", "unpavedroads"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.routing), _translate("OSMtoolsDialogBase", "Routing"))
        self.iso_travel_label.setText(_translate("OSMtoolsDialogBase", "Travel mode"))
        self.iso_unit_label.setToolTip(_translate("OSMtoolsDialogBase", "<html><head/><body><p>Defaults to \'RecursiveGrid\', \'TIN\' not available yet.</p></body></html>"))
        self.iso_unit_label.setText(_translate("OSMtoolsDialogBase", "Isochrone unit"))
        self.iso_unit_combo.setToolTip(_translate("OSMtoolsDialogBase", "<html><head/><body><p>Defaults to \'RecursiveGrid\', \'TIN\' not available yet.</p></body></html>"))
        self.iso_range_text.setToolTip(_translate("OSMtoolsDialogBase", "<html><head/><body><p>Comma separated list of isochrone ranges</p></body></html>"))
        self.iso_range_unit_label.setText(_translate("OSMtoolsDialogBase", "mins"))
        self.iso_range_label.setToolTip(_translate("OSMtoolsDialogBase", "<html><head/><body><p>Comma separated list of isochrone ranges</p></body></html>"))
        self.iso_range_label.setText(_translate("OSMtoolsDialogBase", "Isochrone ranges"))
        self.iso_location_label.setToolTip(_translate("OSMtoolsDialogBase", "<html><head/><body><p>Will print lat/long, municipality, district and country of mapped location.</p></body></html>"))
        self.iso_location_label.setText(_translate("OSMtoolsDialogBase", "Prints location here"))
        self.iso_location_button.setToolTip(_translate("OSMtoolsDialogBase", "<html><head/><body><p>Click on map canvas to select a point source for accessibility area</p></body></html>"))
        self.iso_location_button.setText(_translate("OSMtoolsDialogBase", "Map now!"))
        self.iso_layer_refresh.setText(_translate("OSMtoolsDialogBase", "Refresh List"))
        self.iso_layer_label.setText(_translate("OSMtoolsDialogBase", "Point Layer"))
        self.iso_layer_combo.setToolTip(_translate("OSMtoolsDialogBase", "Input Layer must be of type \'Point\' and in EPSG:4326"))
        self.iso_layer_check.setText(_translate("OSMtoolsDialogBase", "Use Layer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.iso), _translate("OSMtoolsDialogBase", "Isochrones"))
        self.matrix_travel_label.setText(_translate("OSMtoolsDialogBase", "Travel mode"))
        self.matrix_start_refresh.setText(_translate("OSMtoolsDialogBase", "Refresh List"))
        self.matrix_start_combo.setToolTip(_translate("OSMtoolsDialogBase", "Input Layer must be of type \'Point\' "))
        self.matrix_start_id_label.setText(_translate("OSMtoolsDialogBase", "Select Unique ID field"))
        self.matrix_start_label.setText(_translate("OSMtoolsDialogBase", "Start Locations"))
        self.matrix_end_combo.setToolTip(_translate("OSMtoolsDialogBase", "Input Layer must be of type \'Point\' "))
        self.matrix_end_refresh.setText(_translate("OSMtoolsDialogBase", "Refresh List"))
        self.matrix_end_id_label.setText(_translate("OSMtoolsDialogBase", "Select Unique ID field"))
        self.matrix_end_label.setText(_translate("OSMtoolsDialogBase", "End Locations"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OSMtoolsDialogBase", "Matrix"))

